create database companys;
use companys;
create table employee(id int(10),name varchar(45),designation varchar(40),salary float,city varchar(20));
desc employee;
insert into employee values(1,'ram','manager',15000.00,'Salem'),(2,'Hari','manager',15000.00,'Salem'),(3,'ram','manager',25000.00,'karur'),(4,'suresh','analyst',20000.00,'Madurai'),(5,'dhinesh','ceo',90000.00,'thiruvarur'),(6,'abi','team manager',45000.00,'Salem'),(7,'aparna','developer',50000.00,'erode'),(8,'kumar','ceo',80000.00,'Trichy'),(9,'rani','tester',25000.00,'Salem'),(10,'raja','analyst',30000.00,'karur');
-- select * from employee;
set sql_safe_updates=0;
update employee set designation='SalesManager' WHERE name='ram';
update employee set city='Delhi' WHERE name='ram';
update employee set salary=60000.00 where name like 'H%';
Select * from employee;
select * from employee where name='ram' or salary=25000.00;
select * from employee where salary >30000.00 and salary < 50000.00;
select * from employee where city ='karur';
alter table employee add dept varchar(30);
update employee set dept='IT' where id=1;
update employee set dept='CSE' where id=2;
update employee set dept='CSE' where id=3;
update employee set dept='IT' where id=4;
update employee set dept='IT' where id=5;
update employee set dept='CSE' where id=6;
update employee set dept='IT' where id=7;
update employee set dept='CSE' where id=8;
update employee set dept='IT' where id=9;
update employee set dept='CSE' where id=10;
select * from employee;
select dept,sum(salary) from employee group by dept having sum(salary)>200000;
select count(salary) from employee;
select upper(name) from employee;
select min(salary) from employee;
select max(salary) from employee;
select min(salary) as 'MinSalary' from employee;
select name as emp_name,salary+500 as salary,salary*0.1 as '10%' from employee;
